### ISSUE TITLE
IPSec interface does not show under Interfaces or Firewall rules

### ISSUE THREAD

**Issue by thomasnilsen** [opnsense/core#1435]
Hi,

I have just configured IPSec and it works very well (up to point where traffic is routed), but when I was going to setup firewall rules for it, it's not there.. I tried to "Assignments" under Interfaces and see if its waiting there, but no luck..

On my dashboard etc the IPSec shows in traffic graphs etc..

best regards
Thomas

**Comment by fichtner** [comment]
Hi Thomas,

Which version? I think this was permanently fixed in 17.1.1: 

https://github.com/opnsense/changelog/blob/master/doc/17.1/17.1.1#L36


Cheers,
Franco

**Comment by thomasnilsen** [comment]
Hi @fichtner 

17.1.2 (installed).

I started at 17.1 but did a update from that to 17.1.1 and then to 17.1.2 if that helps..

best regards
Thomas

**Comment by fichtner** [comment]
Ok, saving the config in any dialog should fix this. If not we need to take a closer look...

**Comment by thomasnilsen** [comment]
That does not do it.. Tried refreshing everything but no luck..

**Comment by fichtner** [comment]
One more in the forum: https://forum.opnsense.org/index.php?topic=4638.0

Maybe it's this: https://github.com/opnsense/core/commit/318426c

Can you try to revert via:

   # opnsense-patch 318426c

And save an unrelated page like e.g. System: Setting: General?


Thanks,
Franco

**Comment by mircsicz** [comment]
I'll check that after a few hours sleep...

**Comment by mircsicz** [comment]
THX Franco, after patching and saving something somewhere the IPsec interface was back in Firewall > Rules.

But the old problem remains the same, I can't connect to the dev's behind the IPsec. It even got worse, can't connect even with the rules on WAN enabled...

**Comment by fichtner** [comment]
@mircsicz need to take a look at that config and why it's breaking the expected logic.. the IPsec pass rules could be gone for the moment: try to reapply the firewall rules with the tab and pass rule in place.

**Comment by mircsicz** [comment]
already done... ;-)

**Comment by mircsicz** [comment]
But no change

**Comment by thomasnilsen** [comment]
My IPSec rule tab has re-appeared, but it's still not shown under interfaces src/dst in rules etc.

**Comment by thomasnilsen** [comment]
This happened when i created a site-to-site vpn with phase1 and phase2 entry..

**Comment by thomasnilsen** [comment]
I can now successfully hide/unhide the IPSec tab under firewalls by enable/disable Phase2 on my site-to-site profile.. So I guess there is some broken logic on the part that decides when to show that tab based on that..

**Comment by AdSchellevis** [comment]
timeout due to inactivity
