### ISSUE TITLE
Nextcloud file extensions are not supported by windows

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3069]
I do not know if exactly this exact problem has already been reported, but the file names are not compatible with windows.

![grafik](https://user-images.githubusercontent.com/34602360/50393504-f0cc1800-0756-11e9-8b31-ce0c6bd484f8.png)

**Comment by marjohn56** [comment]
Speak to Microsoft.. :)

**Comment by fabianfrz** [comment]
It is both: A limitation of Microsoft Windows file names in combination which the Nextcloud Client not handling it.

**Comment by opnsenseuser** [comment]
it´s only up to the ":"

**Comment by opnsenseuser** [comment]
Test on windows:
![grafik](https://user-images.githubusercontent.com/34602360/50405468-6070f000-07b5-11e9-8587-78fde5469597.png)

translated means that 
"A filename can not contain any of the following characters: \ /:*?"< >| "

**Comment by fabianfrz** [comment]
A filename can contain such characters in general (except the slash as that is reserved for the directory separator):

![grafik](https://user-images.githubusercontent.com/3713914/50406515-7d61ef00-07c6-11e9-89f2-c1a37e642704.png)

**Comment by opnsenseuser** [comment]
@fabianfrz but not if you use a windows client and integrate "nextcloud" via network drive. 
So you can´t copy the file to your own computer and then windows reports with the above error message.

**Comment by fabianfrz** [comment]
I explain my point of view:

![grafik](https://user-images.githubusercontent.com/3713914/50545815-cd084680-0c1c-11e9-9da8-7ee8ec938b9b.png)

You have two sides:

* Our side, which is OPNsense uploading the file compliant to the WebDAV protocol. If it answers correctly, the backup is OK. If it answers with an error code, you will see a communication failure in the backup page.
* The other side is the client, who can download files from the nextcloud server using WebDAV or the normal web interface (HTTP). Only the client really knows, on which operating system it is running and it can manage the local restrictions. This is why I see that as the job of the software downloading the file. Assume a vendor developing a operating system which only supports digits and dots as file names. Do I really have to name the file 123.456?

**Comment by opnsenseuser** [comment]
@fabianfrz I do not quite understand why this is such a big problem, simply convert the file so that it can also be read by windows without problems. Instead of the ":" simply take a hyphen and the problem is solved for all.

**Comment by fabianfrz** [comment]
The file name contains the time in a 24h format (hh:mm:ss), which everyone detects as such because it complies with the format everyone expects as a time format. Also the 12h format contains the column (hh:mm:ss pm/am).

It is also incorrect to fix it here because it does not fix the problem at all. If another application designed to run on Linux or BSD put such a file on nextcloud, the problem appears again.

**Comment by opnsenseuser** [comment]
@fabianfrz if that is really so complicated then it would be perhaps the best solution to automatically save the files in two different versions?

**Comment by fichtner** [comment]
Why not change the timestamp to ISO format?

**Comment by fabianfrz** [comment]
also contains columns: https://de.wikipedia.org/wiki/ISO_8601#Zeitzonen

**Comment by fichtner** [comment]
I thought it's possible to omit the ":"

**Comment by fabianfrz** [comment]
my requirements for a good file name:

* easily human readable
* machine sortable
* easy to implement
* makes no trouble in uploading

**Comment by fichtner** [comment]
I'd add "makes no trouble in downloading" and reevaluate from there. The topic will be back sooner or later...

**Comment by opnsenseuser** [comment]
👍

**Comment by opnsenseuser** [comment]
> my requirements for a good file name:
> 
> * easily human readable
> * machine sortable
> * easy to implement
> * makes no trouble in uploading (try to avoid the need of urlencoding)

👍

**Comment by fichtner** [comment]
no progress, closing...
