### ISSUE TITLE
firmware: /ui pages miss css/js after upgrade

### ISSUE THREAD

**Issue by gitdevmod** [opnsense/core#342]
web page with https://fw/ui/ does not display correctly
ex: https://fw/ui/core/firmware/#checkupdate it takes around 10sec to display the page
![capture d ecran_2015-08-25_21-16-12](https://cloud.githubusercontent.com/assets/2040775/9476721/8d969258-4b6e-11e5-9236-fe2c4c9bad48.png)

System:
OPNsense 15.7.9-i386
FreeBSD 10.1-RELEASE-p17
LibreSSL 2.2.2

**Comment by fichtner** [comment]
We've seen this one other time, the package contents not being installed correctly. Can you check if your disk is full:

    # df -h

Console root menu option 12 should upgrade to 15.7.10 ok and fix the GUI if it wasn't due to a full disk. Note that the 15.7.10 update will reboot.

**Comment by gitdevmod** [comment]
It's a vbox dynamic disk of 10GB,
root@OPNsense:~ # df -h
Filesystem      Size    Used   Avail Capacity  Mounted on
/dev/ada0s1a    9.7G    809M    8.1G     9%    /
devfs           1.0K    1.0K      0B   100%    /dev
devfs           1.0K    1.0K      0B   100%    /var/dhcpd/dev

I installed OPNsense from OPNsense-15.7_LibreSSL-cdrom-i386.iso, updated to 15.7.9 from the console menu then updated to 15.7.10 from console menu, the bug still remains

**Comment by fichtner** [comment]
Browser cache maybe? We moved themes around. E.g. Firefox cache handling is very sticky. Try another browser, close and reopen, maybe empty cached css and javascript.

**Comment by mschilt** [comment]
Screenshot looks like a problem I also experienced (somehow the theme was set to 'pfsense_ng' instead of 'opnsense'.  (had to set it to 'simple' and then back to 'opnsense' to restore it completely but this does not work anymore since 'simple' theme is gone with 15.7.10).

@gitdevmod could you try this:
Connect to the box by using your browsers dev tools/network. Watch if you get any 404 back and have a look at the URL of that file (most probably a css file). Do you see any references to the 'simple' or the 'pfsense_ng' theme?

**Comment by fichtner** [comment]
The pfsense_ng issue happens when a pfsense config was imported and affects all pages. It reads like this only happens on the firmware upgrade page?

**Comment by gitdevmod** [comment]
@fichtner I tried firefox and chrominium with removing cache and still the same. It was also the case from ui/proxy
@mschilt I tried to change the theme to simple to try and did not see anything I switched then back to opnsense. The issue is now resolved since I selected opnsense theme (only one theme in the list like you said) in  settings in page and applied
In source code of the ui/firmware page there is no reference to pfsense_ng

**Comment by fichtner** [comment]
@mschilt @gitdevmod is this somehow reproducible? the workaround described by @mschilt seems odd, it points to a bug in the theme load process we've been unable to trigger locally.

**Comment by gitdevmod** [comment]
@mschilt from the opnsense installation there is no access.log file at least in /var/log/lighttpd directory

**Comment by fichtner** [comment]
@gitdevmod last question for today, was the rest of the GUI affected or only the /ui parts?

**Comment by mschilt** [comment]
@gitdevmod great that it is now solved.
@fichtner Happened to me the last time when I was updating (there is another 'issue' regarding the messed up interface order, etc.). For me only the new parts of the gui were affected (/ui/)

**Comment by fichtner** [comment]
Thanks guys, keeping this open for further investigation.

**Comment by gitdevmod** [comment]
@fichtner if I recall correctly, possible way to reproduce:
install 15.7 then upgrade to 15.7.9 select simple theme then change back to opnsense
ui/ display issue appears
update to 15.7.10 still the same
select again opnsense in settings page then apply and ui/ page works now

**Comment by AdSchellevis** [comment]
Found the issue, the new code handled an empty theme tag differently. 
Fixed in https://github.com/opnsense/core/commit/358318954034bf5a9410c3bd05346fbcd73b7ace

**Comment by fichtner** [comment]
Could reproduce... closed, thanks!
