### ISSUE TITLE
New IPsec GUI broken, generates flawed ipsec.conf

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#345]
I've just updated to OPNsense 15.7.10-amd64. While trying to change my IPsec configuration I've noticed the following defects:

* CRITICAL: When configuring a Phase 2 tunnel and setting P2 protocol to ESP, this setting is ignored. The GUI will show an empty value for P2 protocol and the ipsec.conf will not contain the required "esp" line.

* When changing an existing Phase 1 entry, the value for "Hash algorithm" will always be shown as "MD5" in the edit-screen, although it is configured to something else (i.e. AES).

* When If you change the Phase 1 "Hash algorithm" to i.e. AES256 and save the changes, the GUI will show it as "AES" instead of "AES256". (Old configurations still show up as "AES256"; this will only change to the wrong value if you edit them.)

**Comment by AdSchellevis** [comment]
Sorry about that Frank, there will be a small update tomorrow.

issue one is fixed in https://github.com/opnsense/core/commit/3d3c54651598f75abe6c5d4d49bac2a6ab59d255 the others will follow later

**Comment by AdSchellevis** [comment]
fixed point 2 in https://github.com/opnsense/core/commit/ae582a06237b4deaa0ad2a57901368d5f743460b

**Comment by fraenki** [comment]
@AdSchellevis Thanks for the quick fix. Just verified: setting the P2 protocol to ESP is now working again.

Just found another (possibly related) defect:

* When changing the Phase1 "DH key group" setting, it seems to always set it to "5 (1536 bit)", even if I choose a higher or lower group.

**Comment by AdSchellevis** [comment]
issue 3 looks the same as 2, wrong attribute ;( should also be fixed with last commit.

**Comment by AdSchellevis** [comment]
@fraenki your welcome, glad it functions again.
For the key group, is there a specific situation when that fails? For some reason I can't reproduce it.

**Comment by fraenki** [comment]
@AdSchellevis The key group seemed to be related to your second fix.

Another one, I guess:

* The Phase 1 settings "Enable Rekey" and "Enable Reauth" do the exact opposite thing, they disable the options. If I uncheck both options the settings will be set to "yes" in ipsec.conf. I think that the labels on the old GUI reflected this logic by stating "Disable..." instead.

**Comment by fraenki** [comment]
@AdSchellevis Unfortunately issue 3 is not solved, I still see ```ike = aes-sha256-modp2048!``` in ipsec.conf while it _should_ be ```ike = aes256-sha256-modp2048!```.

**Comment by AdSchellevis** [comment]
@fraenki issue 3 is partially fixed in https://github.com/opnsense/core/commit/c26cb800e2945370978f5be174e6d064e45f09d2 
When refactoring the page, I hoped to leave the javascript code intact, unfortunately this code also contains some glitches. when selecting 256 it works, but any other option changes back to 256 when saving again.

I will close this issue later and move the "enable/disable" issue and the non functional dropdown to new issues, both look like they already where in there before the cleanup.
