### ISSUE TITLE
problem with automatic sync of xmlrpc - encode idna message in log

### ISSUE THREAD

**Issue by katamadone** [opnsense/core#4000]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
Had problems with automatic xmlrpc sync, manual sync worked. 
Tested to create an alias at the primary if it will be synced to the backup firewall. It wasn't created at the slave. Stumbled over log messages:
![grafik](https://user-images.githubusercontent.com/48495427/77479385-f6b01d80-6e1f-11ea-8c13-ea89c6b29858.png)
(actually don't know, if the problems are related). But if I make a copy of a problematic alias entry with a slightly changed name. This entry isn't synced to the backup firewall.

**To Reproduce**
1. Go to Firewall, Aliases
2. Click on 'Add'
3. Enabled, Name 2hg_t_tools_domaincontroller, Content h_t_tools_itops_chtka001,h_t_tools_itops_chzka010,h_t_tools_chzka011 (former created hosts)
4. See error in Firewall Backend Log Files
5. These entries are not created at the backup firewall 
6. with forced sync they appear

if I change the entry 2h_t_tools_chzka011 to 2h_a001 the log error disappears.
I'm very unsure, if I mix now something up with the two problems, have to test that further.

BTW created a copy of every entry in the content, with 2h beginning. That didn't change anything.

Old version was 19.7.7 / 10 not sure if it worked there

**Expected behavior**
alias schould be synced to backup

**Environment**
20.1.3 | 19.7.7

**Comment by katamadone** [comment]
side question: how often should the settings synced to the backup? as far as I remember immediately (after apply)?

**Comment by mimugmail** [comment]
Automatic sync was disabled with 20.1. 
Idna error is bot related to this.

**Comment by katamadone** [comment]
I have to admit, I've overseen that. Thx for clarifying.
Is there an easy way to monitor configuration status on both (synced, unsynced) or as mentioned already a documentation how to sync on regular base?

**Comment by katamadone** [comment]
states it clearly: https://github.com/opnsense/core/issues/3635
but may I ask: is there a command which can be issued at the shell or via cron to push daily a sync?
I think that would be helpful.

**Comment by AdSchellevis** [comment]
From the console, 
```
configctl filter sync
```

or (is what was previously executed)

```
configctl filter sync loads
```

Sends the config to the backup node (it calls `/usr/local/etc/rc.filter_synchronize`)

**Comment by katamadone** [comment]
nice.. thank you! Submitted my solution to the forum as well: https://forum.opnsense.org/index.php?topic=15906.0
For me, that looks like it's working:

done that way:
- Login to your PRIMARY
- cd /usr/local/opnsense/service/conf/actions.d/
- vi actions_hasync.conf


```
[start]
command:configctl filter sync loads
parameters:-c '%s'
type:script
description:run ha_sync
message:cronbased syncing ha
```



after saving:
`service configd restart`


then create a cron job
![grafik](https://user-images.githubusercontent.com/48495427/77756318-38fb7980-702f-11ea-8a00-fbeb9b736205.png)

**Comment by AdSchellevis** [comment]
it's as easy as that indeed, we don't officially support it, but does the trick.

**Comment by AdSchellevis** [comment]
@katamadone by the way, you might want to replace the command with the contents of https://github.com/opnsense/core/blob/0aef984586a61757bb5b99478efa9b2f6085e170/src/opnsense/service/conf/actions.d/actions_filter.conf#L7-L11


saves a configd call :)

**Comment by mimugmail** [comment]
@katamadone keep in mind that this only sync the config.xml!! The backup unit does not generate configs from templates so when switchover occurs unexpected the failover will no work, of you just have out of sync config files.

Otherwise we could just add a description to sync action to call it from cron, but the template reload part is still missing ...

**Comment by katamadone** [comment]
sorry my late answer here. Thank you very much for the informations. May you precise that:
"The backup unit does not generate configs from templates"?

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
