### ISSUE TITLE
GeoIP broken after upgrade to 21.7

### ISSUE THREAD

**Issue by Alives** [opnsense/core#5127]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have a GeoIP floating rule blocking non-USA/non-Canada traffic.  I noticed that nothing is getting through it since upgrading to 21.7.  I removed the rule for now.

1 . Remove the existing GeoIP Alias
2. Updated my maxmind api key
3. Updated and set the maxmind URL to the "GeoLite2 ASN: CSV Format" with my api key in the URI `https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=hunter2&suffix=zip`
4. Click `Apply`
5. Refresh and see:
  * `Last updated: 2021-07-27T00:09:16`
  * `Total number of ranges: 2422331`
5. Click `Aliases` tab
6. Click `+` (Add)
7. Name: `GeoIP_Allow`
8. Type: `GeoIP`
9. `IPv4` and `IPv6` checked
10. Click `America` pulldown
11. Click `Canada`
12. Click `United States`
13. Click `Save`
14. Click `Apply`
15. CPU fan spins up, after about 30 seconds I get an Alias alert: `Invalid argument. [GeoIP_Allow]`

Software version used and hardware type if relevant, e.g.:
OPNsense 21.7-amd64
Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 cores)

**Comment by AdSchellevis** [comment]
For a moment I had the impression that this was new, but `net.pf.request_maxcount` doesn't seem to be changed between versions. The default maximum size for a table is 65535 entries, which is too little for your selection. If you set net.pf.request_maxcount to something high enough in the tunables you should be good.

For the time being I think we should add a reference in the error, not sure if this will be the final solution.

**Comment by fichtner** [comment]
Adjusting maximum table entries is required anyway and automatically sets this sysctl as well. I don’t think there is need to point people to something that another part of the system already takes care of if properly configured in the first place?

**Comment by AdSchellevis** [comment]
@fichtner well, not sure what you mean, but without bogonsv6 configured you're default is likely to end up as 65535

https://github.com/opnsense/core/blob/0e7097cfb1f2bd19c402d3178d7a0259be6ff91a/src/etc/inc/filter.inc#L396-L408

https://github.com/opnsense/src/blob/bdb244c37d3f247f7db8638b1dad5f625af791bd/sys/netpfil/pf/pf.c#L380

**Comment by Alives** [comment]
It'd be nice to have a checkbox in the GeoIP settings to allow the download_geoip function to automatically increase this value as necessary. In my case the way this broke was by blocking ALL inbound traffic, which was catastrophic.

**Comment by Alives** [comment]
FWIW this value was not set in my previous backups, but after upgrading to 21.7 it needed to be increased beyond the default of 1000000 which is what the http gui showed it as.

**Comment by fichtner** [comment]
@AdSchellevis my point is, referring to filter.inc, is that once you set maximumtableentries the sysctl is set accordingly. The fix for the error is therefore not to raise net.pf.request_maxcount but maximumtableentries so net.pf.request_maxcount can be raised symmetrically. Manually raising net.pf.request_maxcount only will still require users to set maximumtableentries later and the whole step and support can be avoided by doing it right away and ignoring net.pf.request_maxcount complications. The code tries to handle this in a way that we can use it like it never existed before.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
I can't find a reason why the behaviour would be different between 21.1.x and 21.7 (my test machine on 21.1.x acts the same on 21.1.x), but if we do want the `table-entries` and `net.pf.request_maxcount` to be aligned, we should ditch the `is_bogonsv6_used()` as they won't be aligned in the current situation when bogons aren't fetched.... (which sounds at least confusing)

**Comment by g-a-c** [comment]
> I can't find a reason why the behaviour would be different between 21.1.x and 21.7 (my test machine on 21.1.x acts the same on 21.1.x)

It wasn't even that wide, this seems to have changed between 21.7_r2 and 21.7. I was running the development builds before ~12pm BST on Wednesday 28th, then upgraded when the final version was released and that's when the ThinkBroadband quality monitor dropped off and started showing my line was down because their pings were being blocked due to the empty GeoIP table.

I have the git backups enabled for my config and don't see any changes in the history that could have caused this - could it have been coincidental growth on the Maxmind side of things? I don't know what the schedule of GeoIP updates on OPNsense is but the reboot during the upgrade may have caused my firewall to fetch a new GeoIP database which just happened to blow out the maximum table size for the countries I was including in a particular alias? I'm clutching at straws a little now though...

**Comment by AdSchellevis** [comment]
> I have the git backups enabled for my config and don't see any changes in the history that could have caused this - could it have been coincidental growth on the Maxmind side of things?

I would expect that's the case indeed,  the current size of `sysctl net.pf.request_maxcount` and the current number of records in the alias would probably explain if that's a reasonable assumption.

> I don't know what the schedule of GeoIP updates on OPNsense is 

It should fetch daily, but given that maxmind also has an interval it might be longer as well:
https://github.com/opnsense/core/blob/17dff052941d113a587d1d6bc62a58a7893250ed/src/opnsense/scripts/filter/lib/alias.py#L181

**Comment by g-a-c** [comment]
> I would expect that's the case indeed, the current size of `sysctl net.pf.request_maxcount` and the current number of records in the alias would probably explain if that's a reasonable assumption.

I've changed it now but I believe the size _would_ have been `1000000` based on your explanation - I didn't manually override anything until today, but I do have IPv6 bogons enabled.

The total number of entries in the affected table (which includes GB, US, and AT) is (assuming this is the correct command):

```sh
root@opnsense:~ # pfctl -t PermittedCountries -Ts | wc -l
 1616593
```

So it would have had to be a heck of a coincidence to suddenly jump up 600k+ entries and break the original `1000000` limit I think.

**Comment by kulikov-a** [comment]
US-IPv6 table contains 1511514 lines )

**Comment by g-a-c** [comment]
Yeah, I've bumped the max table size to `4000000` just as a guess and it now works fine.

But my table was working OK with 21.7_r2, and failed with 21.7, even though there seems to have been nothing changed between them with regards to the max table size, and to have the table jump from <1m entries to 1.6m in the space of a couple of days seems like an improbably big delta

**Comment by AdSchellevis** [comment]
@g-a-c with bogons enabled, the table size is defined as :

https://github.com/opnsense/core/blob/0e7097cfb1f2bd19c402d3178d7a0259be6ff91a/src/etc/inc/filter.inc#L866-L871

I couldn't find a quick reason why the pf defaults should be different, but maybe later I can test on another box. The one with bogonsv6 enabled has this value set to 1.000.000 by default, which is more than enough.

**Comment by kulikov-a** [comment]
@g-a-c

> but after upgrading to 21.7 it needed to be increased beyond the default of 1000000 which is what the http gui showed it as..
even though there seems to have been nothing changed between them with regards to the max table size, and to have the table jump from <1m entries to 1.6m in the space of a couple of days seems like an improbably big delta

possible, but on the other hand table-entries=1.000.000 (which as @AdSchellevis  said is sufficient for most cases) is not enough to import a 1.511.513  size table for any OPN version. therefore, of the two options, a sudden increase of US-IPv6 data seems more likely to me.
we can wait for tuesday, when, as I understand it, the GeoIP db should be updated - maybe something will change again.
maybe then it is worth considering the possibility of increasing `table-entries` and `request_maxcount` to 5.000.00 in cases when geoip url is present in config

**Comment by AdSchellevis** [comment]
@kulikov-a to be honest, I rather would like to stay away from making things more conditional here. the bogons condition is already quite confusing to be honest, explaining where to increase the table size might also be enough. A "progress bar" of the amount of entries used verses the maximum might be a nice addition too, although counting the intended "current" is a bit tricky.

**Comment by kulikov-a** [comment]
@AdSchellevis so may be we can compare table size with `table-entries` value before update at:
https://github.com/opnsense/core/blob/41b311ecc28520757b5cc38ccd3999d842e4306f/src/opnsense/scripts/filter/update_tables.py#L157-L159
?
in this case error message will be mor accurate and specific

**Comment by g-a-c** [comment]
But isn't the maximum table size shared across all tables? So you would have to do that comparison across every incoming table in order to figure out what the total size of entries would be after the entire operation. Then if it looked like the total afterwards would be over the limit you could bail out with an error message? Otherwise it would be possible for all tables to be beneath the limit individually, but for `pf` to complain when you try to load all of them?

**Comment by Alives** [comment]
I'm concerned that there's the unknown of this cronjob pulling in more tables than are "tuned" for in the settings.  In my experience when GeoIP couldn't update the alias, all my incoming traffic was then blocked, locking me out.  What are the consequences for setting this tunable to something ludicrously high?

**Comment by kulikov-a** [comment]
> But isn't the maximum table size shared across all tables?

yes, sorry. stupid idea. we can count records in `/var/db/aliastables/` but not overall number of recors in all tables (with bogons, external aliases etc). 
but we can try to parse 'pfctl -vv -sT' before next table update )
need to test this

**Comment by AdSchellevis** [comment]
> I'm concerned that there's the unknown of this cronjob pulling in more tables than are "tuned" for in the settings. In my experience when GeoIP couldn't update the alias, all my incoming traffic was then blocked, locking me out. What are the consequences for setting this tunable to something ludicrously high?

@Alives mostly resource related (memory / proces exhaustion), with a large enough machine it shouldn't be an issue to upper the limits. (source of the tuneable https://reviews.freebsd.org/D18909)

> yes, sorry. stupid idea. we can count records in /var/db/aliastables/ but not overall number of recors in all tables (with bogons, external aliases etc).

@kulikov-a You can try to calculate the room available, but it has a high risk of regressions. I guess at the end of the day, whatever you do, it will always be unpredictable when the planned content doesn't fit the actual size.  I rather keep the alias parsing as simple as possible, it's already complicated enough as it is. Adding some functionality in the gui to gain insights in the room available with a separate api call might be a reasonable alternative, if you know you're using 90% of the room available, you're more likely to increase the reserved amount.

**Comment by kulikov-a** [comment]
@g-a-c 
It seems that it is not so difficult to add this check: get the current value of a `table-entries`, before loading the next table, get the current total number of records loaded and the number of records in the loading alias. if loading failed and twice the number of records in the table in total with the loaded addresses exceeds the `table-entries`, add a message about the need to change the limit
![max-entries](https://user-images.githubusercontent.com/36099472/127747764-dee89ee3-0805-42d1-a2ff-a2143487d492.PNG)

@AdSchellevis 

>  I rather keep the alias parsing as simple as possible, it's already complicated enough as it is. Adding some functionality in the gui to gain insights in the room available with a separate api call might be a reasonable alternative

It is a great idea to add information about the available room in the gui (for example, in the Firewall: Diagnostics: Aliases), but sometimes it is impossible to predict the sudden growth of the table (url table or external alias). some debug info (in Aliases page or\and general log would be helpful imho)
but if this is the only option, then I will try to play with it)

**Comment by AdSchellevis** [comment]
@kulikov-a Well, memory exhaustion is why the limits exist, so I don't think we can solve that. My thinking was more in the context of always show the reserved room and "available" room on the alias page, so it's easier to asses if there is a risk for the user. In order to do that, we should add an isolated alias to calculate the number of records (using a merge between the pf table and the aliases directory) compared to the defined current maximum entries.

**Comment by kulikov-a** [comment]
@AdSchellevis 

> whatever you do, it will always be unpredictable when the planned content doesn't fit the actual size.

very very true. a thousand apologies )
the behavior is unstable (the overall records count may even exceed the `table-entries` limit without errors. but at next moment the table update errors may appear or an error occurs when reading bogons tables on `pfctl -o basic -f /tmp/rules.debug`). so its difficult to give advice only based on the calculation of the total number of records and the `table-entries` limit.

although adding error logging to the general log to `update_tables.py` and adding limit and total lines count info to this message still seems convenient to me (now the fact of an error in updating the table is not reflected in the log in any way imho)

>  In order to do that, we should add an isolated alias to calculate the number of records (using a merge between the pf table and the aliases directory) compared to the defined current maximum entries.

 sorry, can you explain in more detail? I seem to be missing something again
I tried to simply extend the api with the function of getting the current total number of records loaded by pf (`pfctl -vv -sT`) and the `table-entries` limit (`pfctl -sm`). and attached the result to the aliases page

https://user-images.githubusercontent.com/36099472/127776386-5b4b81b2-378d-44d2-ba93-a6db4a8151b0.mp4

**Comment by AdSchellevis** [comment]
> very very true. a thousand apologies )

not needed at all, we're just working towards an acceptable solution :)

> although adding error logging to the general log to update_tables.py and adding limit and total lines count info to this message still seems convenient to me (now the fact of an error in updating the table is not reflected in the log in any way imho)

We should probably flush the messages to syslog as well indeed, even if the raw error message isn't perfect. I'm just not sure anymore if we should try to guess what the message was (which more or less was my initial commit). In theory there could be more different reasons why things go wrong.

> sorry, can you explain in more detail? I seem to be missing something again
> I tried to simply extend the api with the function of getting the current total number of records loaded by pf (pfctl -vv -sT) and the table-entries limit (pfctl -sm). and attached the result to the aliases page

Well, I do think we should add an api command that tries to count the number of records, but since failed attempts end up in empty tables, we should probably use the contents of `/var/db/aliastables/` for those tables currently being empty.

The screencast from a user perspective is exactly what I meant, looks good, may need a bit of work on formatting, but functionally quite practical, thanks!

**Comment by kulikov-a** [comment]
> I'm just not sure anymore if we should try to guess what the message was (which more or less was my initial commit). In theory there could be more different reasons why things go wrong.

agree. so I would suggest adding this as debug info only. not as a suggestion of a solution. something like
![alias_error_log_debug](https://user-images.githubusercontent.com/36099472/127779163-e2a4a971-47d1-4f7b-9f50-8048b14734d2.PNG)

> Well, I do think we should add an api command that tries to count the number of records, but since failed attempts end up in empty tables, we should probably use the contents of /var/db/aliastables/ for those tables currently being empty.
hm. need to think about how to neatly catch such tables (with 0 addresses in `pf ` and non-empty files in /var/db/). thanks!

**Comment by AdSchellevis** [comment]
@kulikov-a I would probably leave it with the pfctl error (cannot allocate memory), since the gui will tell you the numbers anyway (with your other change). but I'll let you play with it for a while, if there's something to review, just open a PR

**Comment by fichtner** [comment]
> So it would have had to be a heck of a coincidence to suddenly jump up 600k+ entries and break the original `1000000` limit I think.

More reports about US/Canadian GeoIPs causing invalid argument messages: https://www.reddit.com/r/OPNsenseFirewall/comments/owcz4x/217_geoip_settings_wiped_out/

Since they could fix it later I assume the lists have since reverted their issues.

Note that 21.1 and 21.7 kernels behave the same way in this area and are not a "major" upgrades in this regard. Seeing something during 21.1 -> 21.7 just indicates something happened around the same time as it would in any 21.1.x -> 21.1.y minor update.


Cheers,
Franco

**Comment by kulikov-a** [comment]
its tuesday an geoip db is updated. USipv6 table is 479047 records long (again?)

**Comment by smalchow** [comment]
I don't know if it helps, but i have the problem as well, specifically using Ireland, Czech Republic, Germany and Morocco.
I can put all except Germany in one list, the second i add germany i get the "invalid argument" error.

Here is the output of the count for the different aliases

root@XXX:~ # pfctl -t GEOIP_IE -Ts | wc -l
    5408
root@XXX:~ # pfctl -t GEOIP_DE -Ts | wc -l
   26109
root@XXX:~ # pfctl -t GEOIP_CZ -Ts | wc -l
    5115
root@XXX:~ # pfctl -t GEOIP_MA -Ts | wc -l
    2621
root@XXX:~ # pfctl -t COUNTRIES_TEST -Ts | wc -l
   13144

----

Then i add something tiny like Andorra (206 entries) and it still works.

Belgium: 4224 OK
Sweden: 12795 OK

Now a total of 30369 in the COUNTRIES_TEST entry

Add Gibraltar and Slovenia with a total of 1138 entries, bringing the COUNTRIES_TEST to 31507.

And so on, and so so.

It seems as if i hit that problem at the 32768 limit (can really do that exactly) but maybe a variable changed ?

And also a list that i had before with a few countries worked and does not work anymore.

Last but not least, i saw this error already BEFORE 21.7, it must have been introduced somewhere in the 21.1.x line if i would have to guess somewhere before 21.1.7

**Comment by smalchow** [comment]
One small addition, the Alias that gave me the "invalid argument" error still was working (firewall wise) it seems to be a problem purely in the GUI

**Comment by kulikov-a** [comment]
its hard to tell without knowing your `table-entries/net.pf.request_maxcount` limit (can check in Firewall: Diagnostics: pfInfo:Memory) and size of other aliases. but  "invalid argument" error with a high probability indicates that these limits are insufficient for Alias (re)load.

> One small addition, the Alias that gave me the "invalid argument" error still was working (firewall wise) it seems to be a problem purely in the GUI

no imho, not just gui. Alias working but with old Alias content - Alias not updated. Moreover, attempts to update this alias will be repeated every minute. which in the case of huge tables can affect performance imho

**Comment by kulikov-a** [comment]
@AdSchellevis draft PR is almost ready
just 3 questions )
-is this formatting better ?
-may i add some statistic file in  /var/db/aliastables/ ?
-and once again about adding some debug info to the syslog message: progress bar shows only overall records count. nowhere in the gui there is no way to find out the size of the failed table (users need to check table-file in  /var/db/aliastables/ or look at progress bar enabling and disabling alias and compare values)?
maybe we can write messages like: "Error loading alias [AliasName](348117 records): Invalid argument" ?

https://user-images.githubusercontent.com/36099472/128082543-c3e0e07e-d664-4e78-9b9d-f091f4abec4b.mp4

**Comment by AdSchellevis** [comment]
@kulikov-a let me try to answer one by one:

> -is this formatting better ?

I think we can fiddle a bit with the position, but that doesn't matter for now.

> -may i add some statistic file in /var/db/aliastables/ ?

Depending the reason, I'm not sure it's needed, but if you think it is, go ahead and we can discuss approach and code later.

> -and once again about adding some debug info to the syslog message: progress bar shows only overall records count. nowhere in the gui there is no way to find out the size of the failed table (users need to check table-file in /var/db/aliastables/ or look at progress bar enabling and disabling alias and compare values)?
> maybe we can write messages like: "Error loading alias [AliasName](348117 records): Invalid argument" ?

I don't think it's needed if we count the correct numbers, I tried to explain that earlier, but I don't think I did explained it properly. If we count the number of entries that are "planned" to be in there, you can have more than 100% usage, which is exactly what I was aiming for. The only challenge are the aliases that aren't managed by OPNsense (dynamic ones for example), they do fill up space, but don't have a file representation on disc we can easily count. 

Changing the (log) message to something that's always right (as you suggested "Error loading alias ...") is a good idea, if pfctl reports any other message, we still couldn't load the alias (containing X records).

**Comment by smalchow** [comment]
Ok, let me be more specific, the problem is NOT within pfctl - i think that is pretty clear, if i take one of the aliases (e.g the one i created for Germany) and add it to the test alias, like so

for i in `pfctl -t GEOIP_DE -Ts`; do pfctl -t COUNTRIES_TEST -T add $i; done

i do not have a problem at all and after that the alias is bigger than using the GUI allows

root@XXXX:~ # pfctl -t COUNTRIES_TEST -Ts | wc -l
   58271

**Comment by fichtner** [comment]
It simply suggests the default maximum table entries is bigger than the maximum request size since you add each one individually. If you add them all at once it fails (inside pfctl).

**Comment by kulikov-a** [comment]
@smalchow 
can you try to use `pfctl -t tablename -Treplace -f` as update script do?
different limit values required when using pfctl with -Tflush/-Tadd, -Treplace and add records one by one.
When you add record one by one you only may hit the limit with overall records count at some moment.
When you reload table with the new one (-Treplace -f) you need `table-entries` be at least twice the size of the table.
its all about pfctl, not GUI
@AdSchellevis 
got it. thanks!

**Comment by smalchow** [comment]
I assume this is what you are interested in

[root@XXXX ~]# pfctl -t COUNTRIES_TEST -Treplace -f ./GEOIP_DE
26108 addresses added.
[root@XXXX ~]# pfctl -t GEOIP_DE -Ts | wc -l
   26109
[root@XXXX ~]# pfctl -t COUNTRIES_TEST -Treplace -f ./GEOIP   
pfctl: Invalid argument.
[root@XXXX ~]# cat ./GEOIP | wc -l
   56272
[root@XXXX ~]# 

And yes, you are right, if i replace a large amount as one chunk, there is a problem, i did a few more tests and up to the something like 32k limit it seems fine and then it breaks.

How about emptying the alias on modification and then iterate through the new/added/modified aliases, basically like i did ?

**Comment by AdSchellevis** [comment]
> don't know what the devs will say, but imho it makes sense to use -Treplace instead of -Tflush -Tadd. on failure we are at least left with the old table content and not an empty one

I think that's ok, would have similar behaviour as a filter reload if I'm reading this right, we do need to test it though.

**Comment by smalchow** [comment]
I check the table on different machines, on the one i was testing

table-entries hard limit   200000

on another one 1 Mio.

With one Mio, putting DE,BE,SE into one alias works, with 200.000 it does not. Both machines have the same amount of memor though, how is this calculated ?

**Comment by fichtner** [comment]
Geez, it's already fixed in 21.7.1 and this is a lot of typing :D

**Comment by smalchow** [comment]
And i can confirm, it works (at least on my machines) 

Thanks

**Comment by AdSchellevis** [comment]
time to close this issue, visibility has been improved with https://github.com/opnsense/core/pull/5142 and table size is unconditional now due to https://github.com/opnsense/core/commit/f969d857ad6f59a791c9d1c02ef9d851e5db58fe

**Comment by TheHellSite** [comment]
I am still facing issues with the GeoIP tables.

`Error loading alias [ALL_geoips]: Invalid argument. {current_size: 459310, new_size: 805683}`
Table size:  81% (807082/1000000) 

I basically selected all countries from the list, except for my home country and the United States.
As soon as I add the US and click Apply, I get the error above. It also seems that the alias is not updated even though the table size grows significantly. http://ping.pe/ is still able to ping my ip address from US servers.

**Workaround**
However, the US is working fine if a create a 2nd alias (US_geoips) and a 2nd firewall rule besides my "ALL_geoips".
With those two aliases and firewall rules http://ping.pe/ is finally unable to further ping my IP address.

**Comment by kulikov-a** [comment]
@TheHellSite 
imho everything works as it should. to update the `[ALL_geoips]` table, `pfctl` may need space of 459310 + 805683. which exceeds the limit of 1mil. Thus, you can either increase the limit or create a separate table. you chose the second option and it works.
although imho now the overall number of records is too close to the overall limit.
at some point, the number of records in some table may suddenly increase (https://github.com/opnsense/core/issues/5127#issuecomment-890150717) and table updates may stop working.

**Comment by TheHellSite** [comment]
> imho everything works as it should. to update the `[ALL_geoips]` table, `pfctl` may need space of 459310 + 805683.

I think, you are misinterpreting the error. "new_size" is not the size that gets added to the list, it is the size of the whole alias after hitting apply.

**ALL_geoips --> disabled, with all countries selected**
- Overall: 0% (1407/1000000) 
- ALL_geoips = 0

**ALL_geoips --> enabled, with all countries selected**
- Overall:  81% (807082/1000000) 
- Alias: 0
- `Error loading alias [ALL_geoips]: Invalid argument. {current_size: 0, new_size: 805683}`

I know this will be a large alias/list but the overall size isn't different any different when using two separate aliases.
Also it should still be working I guess.

**Comment by kulikov-a** [comment]
> "new_size" is not the size that gets added to the list, it is the size of the whole alias after hitting apply

yes. but )
records not just flushed and added by pfctl in script. it "replaced". so it need space for "old" (current_size)  records and "whole new table" (new_size) for processing. (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235754#c1)

> It seems that there is still a limit for a single alias on how many entries it can take before getting stuck.

yes. to simplify: the limit should be at least twice the size of the largest table being updated

**Comment by TheHellSite** [comment]
> yes. but )
> records not just flushed and added by pfctl in script. it "replaced". so it need space for "old" (current_size) records and "whole new table" (new_size) for processing.

I figured that. But why is it still giving me the error when I
1. disabling the alias and hitting apply so the tables get flushed
2. enable the alias with us selected and apply?

This way there should be enough space for the whole 800k table given the space of 1m.

**Comment by kulikov-a** [comment]
ah, sorry. here I probably made a mistake (already forgot a little. https://github.com/opnsense/core/issues/4669#issuecomment-773406145). `-Treplace` may require twice the number of imported table lines, regardless of whether the table was flushed before.

**Comment by TheHellSite** [comment]
So my best bet is still to increase the overall table size?

**Comment by kulikov-a** [comment]
yes, i think so

**Comment by TheHellSite** [comment]
I just created a tunable `net.pf.request_maxcount` with a value of `2000000`, applied it and rebooted the firewall.

Alias page is still showing a limit of 1.000.000 so does the shell.
```
root@FIREWALL:~ # sysctl net.pf.request_maxcount
net.pf.request_maxcount: 1000000
```

**Comment by kulikov-a** [comment]
@TheHellSite  try to change Firewall Maximum Table Entries at Firewall: Settings: Advanced
no reboot required
(sysctl will be set equal to this `table-entries` value)

**Comment by Stoony1** [comment]
> @TheHellSite try to change Firewall Maximum Table Entries at Firewall: Settings: Advanced no reboot required (sysctl will be set equal to this `table-entries` value)

Hat geklappt vielen dank. 

Habe die einträge auf 10000000 gesetzt.

**Comment by EHRETic** [comment]
Doubling the default value also fixed it for me, thanks a lot! 😉👌
