### ISSUE TITLE
firmware: freeradius3 package stuck on update

### ISSUE THREAD

**Issue by EdwinKM** [opnsense/core#6167]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

[ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Update to the latest version (released friday) seemed to work but after the reboot it was not really updated. (or at least not to the latest version). Retrying to update again failed. A lot of errors about missing freeradius stuff.

Created forum topic and seem more users with similar results. Maybe something is wrong?

More details topics:
  https://forum.opnsense.org/index.php?topic=31313.0
  https://forum.opnsense.org/index.php?topic=31320.0

Note: After some hours my RADIUS died and my connection was dropped. Not really sure if related. But it seems too coincidental.

In my case if uninstalled the RADIUS plugin. Updated OPNsense en reinstalled the plugin. I seem now at the latest version. But still i can not connect via RADIUS. Note: wifi is working fine for the normal wpa2 protected vlans.

**To Reproduce**

1. Use the update feature. I was on an older version. (can not really verify currently because LAN is completely on the RADIUS. But guess 5 minor versions behind).
2. Update
3. It rebooted as if successful update
4. See version dashboard still behind
5. Note: if i press update i now also get 2 popups with the "information wall of text". This seems also (another) bug?

**Expected behavior**

Updated till latest version (and working RADIUS)

**Describe alternatives you considered**

Currently creating a debian vm with RADIUS server to validate the issue.

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

About 5 minor versions behind. Qotom mini pc.

**Comment by Gamertech** [comment]
22.7.8 > 22.7.9 - Same issue. Update log is identical to that in the OP of the first forum link.

Update gets stuck on freeradius and fails with missing files, and partially rolls back to 22.7.8. Further upgrade attempts fail.

**Comment by fichtner** [comment]
Likely same as #616 too

**Comment by EdwinKM** [comment]
to make it clear. Although i used the workaround to make the opnsense update work. RADIUS authentication does not work. I use the same exported certs now with my own debian radius and this seems to work fine.

To me unknown how many users are using RADIUS and of it also broke for them....

**Comment by fichtner** [comment]
Let's take a look at this from a more grounded perspective: the bug with the install/update is probably in the FreeBSD package manager and the configuration issue might be in the 3.1 or 3.2 changes. I'm not sure if this was avoidable, FreeBSD port was stuck in 3.0 for a very long time.

**Comment by EdwinKM** [comment]
i had contact on the forum with a user with a VM with this issue. Can not find it this fast.

**Comment by fichtner** [comment]
I've updated to FreeBSD package manager version 1.18.4 today. But on the surface I have no idea how and why it fails to replace freeradius... most changes are months old or older. Nothing pertains to FreeRADIUS directly. Perhaps when the service is running it holds onto directories making updates impossible, but I've never seen it before.

**Comment by riekelt** [comment]
> I started working on this today, but I may need some testers

If you need a testcase, my opnsense router has this issue I think.

```
[2/11] Extracting freeradius3-3.2.1: .......... done
You should remove /usr/local/etc/raddb if you don't need it any more.
freeradius3-3.0.25: missing file /usr/local/lib/freeradius-3.0.25/libfreeradius-dhcp.a
freeradius3-3.0.25: missing file /usr/local/lib/freeradius-3.0.25/libfreeradius-dhcp.la
freeradius3-3.0.25: missing file /usr/local/lib/freeradius-3.0.25/libfreeradius-dhcp.so
....
freeradius3-3.0.25: missing file /usr/local/share/licenses/freeradius3-3.0.25/catalog.mk
pkg-static: Fail to set time on /var/log/radacct:No such file or directory
Starting web GUI...done.
```

The update fails and will not reboot as described in the issue. `opnsense: 22.7.6 -> 22.7.9_3`

**Comment by fichtner** [comment]
CC @zi0r as committer of the ports change

**Comment by zi0r** [comment]
I'm not sure here--the update from 3.0.x -> 3.2.x worked fine for me under FreeBSD 12.3 (amd64).

**Comment by Gamertech** [comment]
```
OPNsense 22.7.8-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022
```

`# mkdir -p /var/log/radacct /var/run/radiusd` doesn't do anything. The directories already existed, but still get the 
`pkg-static: Fail to set time on /var/log/radacct:No such file or directory` error, as well as all the missing file errors. Maybe permissions related?

**Comment by zi0r** [comment]
Is anyone able to reproduce this under straight up normal FreeBSD?

**Comment by putnam** [comment]
I have this installed and cannot upgrade or receive security updates right now. Is this package maintained? I guess I can just remove it and run Freeradius on something else.

**Comment by mimugmail** [comment]
Just remove the plugin and install again

**Comment by Gamertech** [comment]
Several people so far have stated that OPNsense updates and the plugin reinstalls by doing that, but RADIUS authentication no longer works afterwards, which would be a problem.

**Comment by fichtner** [comment]
Just lock freeradius3 package from GUI, problem solved with update and operability for the time being in under 5 seconds. There is an upstream bug as well and it needs a new version:

https://github.com/FreeRADIUS/freeradius-server/issues/4820
https://github.com/FreeRADIUS/freeradius-server/issues/4785

**Comment by Gamertech** [comment]
All the time I've used OPNsense, I never knew about the lock button for packages in the GUI :stuck_out_tongue: 

That worked thank you @fichtner

For other users with the same issue, in `System/Firmware/Packages` click the lock icon next to freeradius and os-freeradius then run the update as normal.

Now I just need to remember to unlock them when the fix arrives.

**Comment by fichtner** [comment]
Glad to hear. I wouldn't recommend locking `os-freeradius` plugin as you won't get any plugin fixes this way. `freeradius3` package alone should work.

**Comment by Gamertech** [comment]
Just a heads up as there was some radius changes. Tested 22.7.10-2 with freeradius3 unlocked but it still fails with the same errors. Locking it again, the OPNsense update completed fine.

**Comment by fichtner** [comment]
I was hoping a bit pkg 1.18.4 would behave better in this regard. Somewhat at a loss here. I don't think this is that specific to OPNsense just missing the proper parameters here to reproduce. Is this ZFS or UFS? Was this a fresh 22.7 install or an older one?


Cheers,
Franco

**Comment by Gamertech** [comment]
For me at least, ZFS and this install's been running since 21.1 I believe.

**Comment by zi0r** [comment]
I've made a commit to the FreeBSD ports tree to bring in the fix for hhttps://github.com/FreeRADIUS/freeradius-server/issues/4785 from upstream.

I have also added a post-install task to create the directory you guys seem to be missing.  It shouldn't be required as this is handled by pkg-plist, but, maybe it will improve things for you.

https://cgit.freebsd.org/ports/commit/?id=6fe12ab2c86d2ac9801365840193637256d51f71

**Comment by Gamertech** [comment]
> I have also added a post-install task to create the directory you guys seem to be missing. It shouldn't be required as this is handled by pkg-plist, but, maybe it will improve things for you.

In my case, the directories were originally created successfully, but the update system refuses to recognise them, saying the directories are missing still. So it seems more like a permissions issue at fault.

**Comment by fichtner** [comment]
@zi0r thanks, much appreciated! this will be in the next minor release 22.7.11

**Comment by Slipperyclock** [comment]
@fichtner  will this minor release resolve the update issues for users attempting to update the OS.  I have been stuck trying to upgrade from 22.7.8 and cant at this time due to the freeradius paths "missing".  What is strange is that the error is accurate "/usr/local/lib/freeradius-3.0.25/" does not exists im showing paths with "/usr/local/lib/freeradius-3.2.1/"

![image](https://user-images.githubusercontent.com/45883233/212920119-9f5dceb6-4f7f-4a85-b299-380907cbf1c8.png)
![image](https://user-images.githubusercontent.com/45883233/212920405-98b9be4b-6579-4d80-86b9-79864e8d7c21.png)


Freeradius Dir
![image](https://user-images.githubusercontent.com/45883233/212921265-7fc6b0f9-1e86-4b94-a1be-584c387d038d.png)

**Comment by Gamertech** [comment]
22.7.11 still fails, the exact same error log :(

**Comment by Slipperyclock** [comment]
Is there any updates or plans for resolution or are those of us with this issue stuck and have to reinstall?

**Comment by fichtner** [comment]
Perhaps UFS error then. have you run fsck in single user mode?

**Comment by Slipperyclock** [comment]
> Perhaps UFS error then. have you run fsck in single user mode?

Thats a good thought.  I copied my configs for freeradius, removed the package and it allowed me to upgrade.

**Comment by mimugmail** [comment]
You can just remove the plugin, upgrade and install again, it will keep the config.

**Comment by fichtner** [comment]
@zi0r pulled in the upstream patch for the auth issue

**Comment by fbruetting** [comment]
I locked that package so that I could run the last 22.7 update by leaving that one package out. Then I started updating to 23.1 and now my SBC is not starting anymore! Be careful! Now I have to order a USB to serial converter for debugging my PCEngins APU2. –.–

Btw.: Is there some quickfix?

**Comment by mimugmail** [comment]
Currently not, for the time being just stay on 22.1.10.

I have a unifi system with 2 radius, one on 22.1.10 which works great, other with 23.1_6 and stucks during EAP TLS auth. 

Not that easy to diagnose cause radius -X runs fine, it sends a challenge to client and dont get a response

**Comment by fichtner** [comment]
What booting issue? You realise locking a package has no effect on major upgrade for other upgrade-breaking reasons?

If in doubt get advice here or in the forum.


Cheers,
Franco

**Comment by fbruetting** [comment]
So I thought, too.

I never have modified OPNsense beyond the obvious cofigurations and it ran and updated without the slightest issue since about 2017 or so. Now with locking freeradius and starting the updating procedure to 23.1, the update failed and it never booted sucessfully since.

So I thought it’s maybe due to that package locking. Maybe it’s instead due to 23.1, I don’t know… until I receive my serial cable and hopefully am able to debug.

**Comment by mimugmail** [comment]
https://github.com/FreeRADIUS/freeradius-server/issues/4878 and https://github.com/FreeRADIUS/freeradius-server/issues/4785 should fix those which are shipped with 3.2.2 (will take a bit when it finds it's way into OPNsense). Especially the first one seems to fit exactly what I'm experiencing too.
