### ISSUE TITLE
IPsec site to site with dynamic DNS results in "unable to resolve %any, initiate aborted" on initialization

### ISSUE THREAD

**Issue by Nadahar** [opnsense/core#6396]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I'll start by stating that I'm not sure if this is indeed a bug or me just misunderstanding things. But, to me it looks like a likely bug.

I'm currently running `OPNsense 23.1.1_2-amd64`. I recently did an upgrade, but I'm not sure from which version that was. I don't think this used to be an issue, but I can't be sure of that either because the tunnel works if initiated by the remote party.

The problem is that if I enable `Allow any remote gateway to connect` under phase 1 IPsec settings, it won't connect to the remote party. It will log `unable to resolve %any, initiate aborted`, and nothing further seems to happen. Both parties (OPNsense in this end, an older pfSense in the other) have dynamically assigned IP addresses and thus use dynamic DNS for resolving the remote addresses. If I initiate the connection from the pfSense installation, the tunnel goes up and everything works just fine. But, initiation from the OPNsense end seems impossible.

If I disable `Allow any remote gateway to connect`, OPNsense will also connect straight away. Why not just leave it disabled then? This is where I'm unsure if I misunderstand something. The "help text" for `Allow any remote gateway to connect` states:
> Recommended for dynamic IP addresses that can be resolved by DynDNS at IPsec startup or update time.

This sounds like something I should have enabled from the description. My understanding is that it won't reject the remote party during initialization if the remote IP doesn't match the remote DNS entry. That might happen just after a change, due to DNS caching before expiry. So, it seems like a good idea not to reject the other party if this situation occurs.

It should however not, as I understand it, affect the "outgoing address" when trying to initiate a connection. The error seems to indicate that it's trying to establish a connection with an undefined remote address. That's not the case, it should still use that specified under `Remote Gateway` when initializing a connection.

**To Reproduce**

I'm not sure what circumstances that's required for this to happen, except that `Allow any remote gateway to connect` must be enabled. This happens even if I put a static IP in the `Remote Gateway` field, as long as `Allow any remote gateway to connect` is enabled. That might be all it takes to reproduce, but to narrow it down a but, I can mention that I'm using IKEv2, IPv4, `Start immediate`, `Mutual PSK`, and `User distinguished name` for both identifiers. It's hard to imagine that the encryption, hashing or phase 2 settings matter as it never comes to any of that.

**Expected behavior**

I expect that it's possible to initiate a IPsec connection even if `Allow any remote gateway to connect` is enabled.

**Environment**

OPNsense 23.1.1_2 (amd64, OpenSSL 1.1.1t)
Intel(R) Atom(TM) CPU C3558 @ 2.20GHz (4 cores, 4 threads)

**Comment by AdSchellevis** [comment]
Reading the migration notes again, this looks like a bug indeed. should be fixed with https://github.com/opnsense/core/commit/24806500c55a51979ec8ff3fac06520e454ce03e 

The `rightallowany` option should be translated to ipv4+ipv6 subnet according to https://wiki.strongswan.org/projects/strongswan/wiki/Fromipsecconf (we switched from ipsec.conf to swanctl.conf in 23.1)

**Comment by Nadahar** [comment]
Can I expect this to be included in a minor release?

**Comment by fichtner** [comment]
23.1.2 next week.

**Comment by Nadahar** [comment]
I just got the new update (`23.1.2`), and I'm afraid the problem is still there - just with a slightly different error message:
> unable to resolve 0.0.0.0/0, ::/0, initiate aborted

**Comment by fichtner** [comment]
Testing the patch beforehand would have been more helpful. 😉

**Comment by AdSchellevis** [comment]
and what does `/usr/local/etc/swanctl/swanctl.conf` look like for this entry (without sensitive data)?

**Comment by Nadahar** [comment]
```
# This file is automatically generated. Do not edit
connections {
    con2 {
        unique = replace
        aggressive = no
        version = 2
        mobike = no
        local_addrs = 85.x.x.119
        local-0 {
            id = userfqdn:XXX@xxxxxx
            auth = psk
        }
        remote-0 {
            id = userfqdn:XXX@xxxxxx
            auth = psk
        }
        remote_addrs = 0.0.0.0/0,::/0
        encap = no
        reauth_time = 28740 s
        rekey_time = 28740 s
        over_time = 60 s
        rand_time = 3000 s
        dpd_delay = 10 s
        dpd_timeout = 60 s
        proposals = aes256gcm16-sha384-modp4096
        children {
            con2 {
                start_action = start
                policies = yes
                mode = tunnel
                sha256_96 = no
                close_action = start
                dpd_action = start
                local_ts = 10.x.x.0/24
                remote_ts = 10.x.x.0/24,10.x.x.0/24
                reqid = 3
                esp_proposals = aes256gcm16-modp4096
                life_time = 3600 s
                rekey_time = 3540 s
                rand_time = 3000 s
            }
        }
    }
}
pools {
}
secrets {
    ike-p1-1 {
        id-0 = userfqdn:XXX@xxxxxx
        secret = xxx
    }
}
# Include config snippets
include conf.d/*.conf
```

**Comment by Nadahar** [comment]
When I disable the remote gateway and check the same file, I can see:
> remote_addrs = [remote DNS address]

..instead of:
> remote_addrs = 0.0.0.0/0,::/0

I think that must be the root of the problem. The idea with the option, as I understand it, is to allow any address to initiate a connection (since it's unknown what it might be). For this firewall to initiate the connection, it still needs a remote address to connect to, so the information must exist in the configuration file somewhere.

Maybe "allow any incoming remote address" should be specified somewhere else than in `remote_addrs` itself?

**Comment by Nadahar** [comment]
StrongSwan's documentation for `remote_addrs` states:
> Remote [comma-separated] address[es] to use for IKE communication. Accepts single IPv4/IPv6 addresses, DNS names, CIDR subnets or IP address ranges. As an initiator, the first non-range/non-subnet is used to initiate the connection to. As a responder, the initiator source address must match at least to one of the specified addresses, subnets or ranges. If FQDNs are assigned they are resolved every time a configuration lookup is done. If DNS resolution times out, the lookup is delayed for that time. To initiate a connection, at least one specific address or DNS name must be specified

I read that as that `remote_addrs` should actually be `[remote DNS address],0.0.0.0/0,::/0` for this to work. The first address will be used when initiating a new connection, while any address must match to accept incoming.

**Comment by Nadahar** [comment]
I can't say if this is a valid test or not, as it seems that OPNsense will regenerate `swanctl.conf` even on a service restart from the web GUI, but I did the following, which does connect successfully:
* I manually edited `swanctl.conf` and sat `remote_addrs = [remote DNS address],0.0.0.0/0,::/0`
* I ran `ipsec down con2` followed by `ipsec up con2`

After doing this, it does connect and my edit is still present in the configuration file. That said, I don't know how to test that the "accept any" part for incoming connections works, but at least outgoing connections connect like they should.

**Comment by AdSchellevis** [comment]
Ok, I think we should have left mobile to default (%any) although that might act the same. To be the connecting party, there should be an address in the list indeed. https://github.com/opnsense/core/commit/3af487bcf65a4d8a32ea999f16f1a932620e80e7 should fix that.

Install on the machine using:

```
opnsense-patch 3af487b
```

**Comment by Nadahar** [comment]
@AdSchellevis With 3af487bcf65a4d8a32ea999f16f1a932620e80e7 it works :+1: 

While I don't know how this impacts mobile clients, it sounds logical to me that it should be left with `%any` given that the server never (?) initiates a connection to a mobile client, so it doesn't need an address to connect to.

**Comment by AdSchellevis** [comment]
@Nadahar ok, thanks for reporting back. I expect that `%any` and `0.0.0.0, ::0/0` are more or less the same for mobile, but better to leave it as it was in this case.

**Comment by fichtner** [comment]
Thanks for confirming. I'm considering this as a hotfix for later this week.
